# ---- build the helium base image ----
FROM  ubuntu:latest AS helium-dev-base

# set noninteractive installation so install works unattended and does not ask any interactive
# questions.
ARG DEBIAN_FRONTEND=noninteractive

### install the ubuntu dev tooling and core utilities needed later
RUN apt-get update && \
    apt-get install -y sudo apt-utils apt-transport-https ca-certificates curl gnupg software-properties-common libssl-dev git wget nano lsb-release jq && \
    apt-get upgrade -y

# Install Azure Cli
RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.asc.gpg && \
    CLI_REPO=$(lsb_release -cs) && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main" > /etc/apt/sources.list.d/azure-cli.list && \
    apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y maven && \
    apt-get install -y azure-cli

# Add the helium user with the default
RUN useradd -u 1000 -U -m -s /bin/bash helium && \
    usermod -aG sudo helium && \
    gpasswd -a helium sudo &&  \
    echo "helium ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/90-helium-users && \
    mkdir -p /home/helium/.azure

### build the final image with all the packages and put the code in there.
FROM helium-dev-base

RUN apt-get update && \
    apt-get upgrade -y

USER helium

# set auth type to use cached CLI credentials
ENV AUTH_TYPE CLI

#expose the app default port
EXPOSE 4120

WORKDIR /home/helium/src

# copy the current folder into the /home/helium/src as we run the code as the helium user
COPY . /home/helium/src

### copy .bashrc and .gitconfig if present
COPY ./dotFiles /home/helium

# change the owner of the helium home dir to the helium user so they can edit the home directory
RUN sudo chown -R helium:helium /home/helium
