# ----- Base Java - Check Dependencies ----
FROM maven:3.6.1-jdk-8 AS base
ENV APPDIR=/app
WORKDIR $APPDIR
ADD pom.xml $APPDIR

#
# ----Build App with Dependencies ----
FROM base AS dependencies
ADD . $APPDIR
# Running mvn clean package will run all the tests as well as package the app up in the jar form
RUN mvn clean package -DskipTests

#
# ---- Release App ----
FROM  openjdk:8-jre-alpine AS release
ENV APPDIR=/app
WORKDIR $APPDIR

### install azure cli
RUN \
  apk add --no-cache curl tar openssl sudo bash jq python3 && \
  apk add --virtual=build gcc libffi-dev musl-dev openssl-dev make python3-dev && \
  pip3 --no-cache-dir install --upgrade pip && \
  pip3 --no-cache-dir install azure-cli

# Create a user
RUN addgroup -g 4120 -S helium && \
    adduser -u 4120 -S helium -G helium && \
    mkdir -p /home/helium/.azure && \
    chown -R helium:helium /home/helium
USER helium

# Note: Every time we update helium version, we must update the jar version below
# Issue is being tracked
COPY --from=dependencies $APPDIR/target/helium-0.1.0.jar app.jar

EXPOSE 4120
CMD ["java", "-jar", "/app/app.jar"]
