name: Java Codespaces Image Build

on:
  push:
    branches:
      - master

    paths:
    - '.devcontainer/Dockerfile'
    - '.github/workflows/codespaces.yml'

jobs:

  docker-codespaces:

    runs-on: ubuntu-latest
    env:
      # These are used in if: conditions
      DOCKER_SET: false

    steps:
    - uses: actions/checkout@v2

    - name: Set conditions
      run: |
        # check that all Docker secrets are set
        if [[ "${{ secrets.DOCKER_PAT }}" != "" && "${{ secrets.DOCKER_USER }}" != "" ]];
        then
          echo "::set-env name=DOCKER_SET::true"
        fi
        
    - name: Docker Login
      if: ${{ env.DOCKER_SET == 'true' }}
      run: |
        # login to dockerhub
        echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Docker Pull
      if: ${{ env.DOCKER_SET == 'true' }}
      run: |
        # Pull the latest image if needed
        # This doesn't have to be a separate step, but makes the output easier to read and debug
        docker pull maven:3.6.3-jdk-11-slim

    - name: Docker Build
      if: ${{ env.DOCKER_SET == 'true' }}
      run: |
        # build release image
        docker build . -t helium-java-codespaces -f .devcontainer/Dockerfile

    - name: Docker Tag and Push
      if: ${{ env.DOCKER_SET == 'true' }}
      run: |
        # tag the repo with :latest
        docker tag helium-java-codespaces retaildevcrew/helium-java-codespaces:latest

        # Push to the repo
        docker push retaildevcrew/helium-java-codespaces:latest
