name: Docker CI By PR

on:
  pull_request:
    branches:
      - master

    paths-ignore:
      - 'docs/**'
      - '.github/workflows/**'

jobs:

  acr-build-push-version:
    runs-on: ubuntu-latest
    env:
      ACR_REG: 'gelatoappsvc'
      ACR_REPO: 'gelatoappsvc.azurecr.io'
      ACR_IMAGE: 'helium-java'
      ACR_TAG: 'stable'
    steps:
      - uses: actions/checkout@v1
      - name: acr-push-build
        run: |
          # You must add the following secrets to github
          #    SERVICE_PRINCIPAL  - your SP Client ID that has ACR Push IAM role
          #    SERVICE_PRINCIPAL_PASSWORD   - the personal access token for the SP Client id
          #    TENANT  - The tenant ID of the subscription of the ACR


          echo "Building Docker image ${ACR_REPO}/${ACR_IMAGE}:${ACR_TAG} from ${GITHUB_REPOSITORY} on ${{ github.ref }}; and pushing it to ${ACR_REG} Azure Container Registry"
          az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL }} -p ${{ secrets.SERVICE_PRINCIPAL_SECRET }} --tenant ${{ secrets.TENANT }}

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.head_ref }}")
          echo $VERSION
          # az acr build -r ${ACR_REG} -f Dockerfile -t ${ACR_REPO}/dev/${ACR_IMAGE}:${VERSION} https://github.com/${GITHUB_REPOSITORY}.git#${{ github.ref }}


  
