name: Docker CI

on:
  pull_request:
    branches:
      - master

    paths:
      - '!docs/**'

    tags:
      - v*

#    DOCKER_REPO  - the docker repository name in the form: organization/repository
env:
  DOCKER_REPO: 'retaildevcrew/helium-java'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to registry
      run: |
        # Login to registry

        # You must add the following secrets to github
        #    DOCKER_USER  - your dockerhub user name
        #    DOCKER_PAT   - the personal access token for dockerhub


        ## login to dockerhub
        echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Build Container
      run: docker build . --file Dockerfile --tag image

    - name: Docker Push
      run: |
        # Tag and push the docker image

        IMAGE_ID=${{ DOCKER_REPO }}

        # tag the image with :beta
        docker tag image $IMAGE_ID:beta

        # Tag image based on repo tag if a github label
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]
        then

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
          # Strip "v" prefix from tag name
          VERSION=$(echo $VERSION | sed -e 's/^v//')
  
          docker tag image $IMAGE_ID:$VERSION
          docker tag image $IMAGE_ID:stable
        fi

        # Push to the repo
        docker push $IMAGE_ID
